services:
  nest-links:
    container_name: links-back-test-task
    build:
      context: .
      dockerfile: ./dockerfile
    networks:
      - postgres-network
    environment:
      DATABASE_URL: ${DATABASE_URL}

networks:
  postgres-network:
    external: true
